const ts = require('typescript'), fs = require('fs'), vm = require('vm'), assert = require('node:assert/strict');
const load = (file, requireFn = require) => {
  const ctx = { exports: {}, require: requireFn, console };
  vm.createContext(ctx);
  vm.runInContext(ts.transpileModule(fs.readFileSync(file, 'utf8'), { compilerOptions: { target: 7, module: 1, esModuleInterop: true } }).outputText, ctx);
  return ctx.exports;
};
const { rankResults } = load('src/utils/comparisonRanking.ts');
const ranking = load('src/utils/comparisonRanking.ts');
const studio = load('src/utils/rankingStudio.ts', name => name === './comparisonRanking' ? ranking : require(name));
const record = (p, strength, deleted = false) => ({ path: Math.random().toString(), generation: { model: { loras: p ? [{ path: p, strength }] : [] }, sample: { prompt: 'test' } }, deleted });
const rs = [record('D:/A/750.safetensors', .6), record('D:/A/750.safetensors', .6, true), record('D:/A/500.safetensors', .8), record('D:/A/750.safetensors', .8), record('D:/B/other.safetensors', 1), record(null)];
let r = rankResults(rs, 'D:/A', false, false);
assert.equal(r.length, 3); assert.ok(r.every(x => x.rank === 1));
r = rankResults(rs, 'D:/A', true, false);
assert.equal(r[0].kept, 2); assert.equal(r[0].total, 3);
r = rankResults(rs, 'D:/A', false, true);
assert.equal(r[2].strength, .6); assert.equal(r[2].rank, 3);
assert.equal(rankResults([], '', false, false).length, 0);
const stacked = record('D:/A/a', 1); stacked.generation.model.loras.push({path:'D:/A/b',strength:1});
assert.equal(rankResults([stacked], '', false, false).length, 0);
const large = Array.from({length: 650}, (_, i) => record('D:/A/model_000000750.safetensors', .6, i % 2 === 0));
const extra = record('D:/B/model_000000750.safetensors', .6);
const matrix = studio.studioData([...large, extra, stacked], 'D:/A');
assert.equal(matrix.combinations.length, 1);
assert.equal(matrix.combinations[0].total, 650);
assert.equal(matrix.combinations[0].kept, 325);
assert.equal(studio.evidenceFor([...large, extra], matrix.combinations[0]).length, 325);
assert.equal(studio.evidenceFor(large, matrix.combinations[0], 'another prompt').length, 0);
assert.equal(matrix.cells.get(studio.candidateKey('D:/A/model_000000750.safetensors', .8)), undefined);
assert.equal(studio.shortCheckpoint('D:/A/model_000000750.safetensors'), 'Step 750');
const batches = [];
const history = load('src/utils/comparisonHistory.ts', name => name === '@/utils/api' ? {apiClient: {post: async (_, body) => batches.push(body.results)}} : require(name));
const dir = fs.mkdtempSync(require('path').join(require('os').tmpdir(), 'aitk-ledger-test-'));
let missing = false;
const ledger = load('src/server/comparisonLedger.ts', name => name === '@/paths' ? { TOOLKIT_ROOT: dir } : name === 'fs/promises' ? { stat: async () => { if(missing) throw Object.assign(Error('missing'), {code:'ENOENT'}); return {}; } } : require(name));
(async () => {
  await history.saveComparisonHistory(large);
  assert.equal(batches.length, 7);
  assert.equal(batches.reduce((n, batch) => n + batch.length, 0), 650);
  assert.ok(batches.every(batch => batch.length <= 100));
  const item = record('D:/A/750.safetensors', .6);
  await Promise.all([ledger.recordResults([item]), ledger.recordResults([item])]);
  let rows = await ledger.readResults(); assert.equal(rows.length, 1); assert.equal(rows[0].deleted, false);
  missing = true; rows = await ledger.readResults(); assert.equal(rows[0].deleted, true);
  await ledger.recordResults([item]); rows = await ledger.readResults(); assert.equal(rows.length, 1); assert.equal(rows[0].deleted, true);
  const second = load('src/server/comparisonLedger.ts', name => name === '@/paths' ? { TOOLKIT_ROOT: dir } : name === 'fs/promises' ? { stat: async () => ({}) } : require(name));
  rows = await second.readResults(); assert.equal(rows.length, 1); assert.equal(rows[0].deleted, true);
  console.log('PASS rankings: folders, ties, rates, overall aggregation, baselines, stacked exclusions; SQLite: deduplication, concurrent inserts, retained deletion evidence');
})().catch(e => { console.error(e); process.exitCode = 1; });
